### ISSUE TITLE
_plugins/gallery_generator.rb:1:in `require': cannot load such file -- exifr (LoadError)

### ISSUE THREAD

**Issue by blay** [ggreer/jekyll-gallery-generator#21] opened 2015-06-28 11:23 UTC
Hi,

I'm trying to install this plugin running Jekyll 2.4.0 on a mac. Copied the files, installed imagemagick and the gems and put jekyll-gallery-generator in my config.yml.

Problem is that is doesn't seem to be able to require exifr although it looks installed alright:

± irb
2.1.2 :001 > require 'exifr'
 => true

Any ideas?

/Magnus

Error:

± jekyll build
Configuration file: /Users/svartfax/Dropbox (Personal)/notes/l.magnu.se/_config.yml
/Users/svartfax/Dropbox (Personal)/notes/l.magnu.se/_plugins/gallery_generator.rb:1:in `require': cannot load such file -- exifr (LoadError)
	from /Users/svartfax/Dropbox (Personal)/notes/l.magnu.se/_plugins/gallery_generator.rb:1:in `<top (required)>'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:58:in `require'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:58:in `block (2 levels) in require_plugin_files'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:57:in `each'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:57:in `block in require_plugin_files'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:56:in `each'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:56:in `require_plugin_files'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/site.rb:74:in `setup'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/site.rb:36:in `initialize'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `new'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `process'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `load'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `<main>'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/svartfax/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ggreer** [comment] 2016-07-07 02:31
I can't reproduce this (also using rvm and OS X) and nobody else has chimed in with "me too" in the past year, so I'm closing it. Sorry I can't be of more help, but it really looks like an issue with your set-up, not my software.

**Closed by ggreer** 2016-07-07 02:31 UTC

**Comment by sheim** [comment] 2016-07-07 02:38
FWIW, I subscribed to this issue because I was getting some similar problems. I since moved on, and don't remember if it was exactly the same issue or just something similar though.
